# Generated by Django 5.1.3 on 2024-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_stars', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('product_feedback', models.TextField()),
            ],
        ),
    ]
